version: 0.2

phases:
  install:
    commands:
      - cd client
      - npm install --legacy-peer-deps

  build:
    commands:
      # - cd client
      - npm run build

artifacts:
  base-directory: client/dist
  files:
    - '**/*'