version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm --prefix client ci --legacy-peer-deps

  build:
    commands:
      - npm --prefix client run build

artifacts:
  base-directory: client/dist
  files:
    - '**/*'

cache:
  paths:
    - client/node_modules/**/*
